// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"todoapp/config"
	"todoapp/internal/delivery/http"
	"todoapp/internal/delivery/http/handler"
	"todoapp/internal/delivery/http/middleware"
	"todoapp/internal/repository/psql"
	"todoapp/internal/usecase/todo"
	"todoapp/pkg/logger"
)

// Injectors from wire.go:

func InitHTTPServer(schema *config.Schema) *http.Server {
	database := psql.NewDatabase(schema)
	todoRepo := psql.NewTodoRepository(database)
	usecase := todo.New(todoRepo)
	loggerLogger := logger.NewLogger()
	handlerHandler := handler.NewHandler(usecase, loggerLogger)
	middlewares := middleware.ProvideMiddleware()
	server := http.NewServer(handlerHandler, middlewares)
	return server
}
